### ISSUE TITLE
Using tablib for export

### ISSUE THREAD

**Issue by TheNcar** [flask-admin/flask-admin#1984] opened 2020-05-11 20:37 UTC
I have a model i was trying to export to an xlsx file:
![image](https://user-images.githubusercontent.com/53982481/81609378-7732d980-93e0-11ea-91a4-7fb385e03080.png)

It kept saying `Export type is not supported`
![photo_2020-05-10_17-58-39](https://user-images.githubusercontent.com/53982481/81609473-a21d2d80-93e0-11ea-9726-4c158e844451.jpg)

I finally solved it by using a different version:
![image](https://user-images.githubusercontent.com/53982481/81609525-ba8d4800-93e0-11ea-9dd0-4e9903c07b01.png)

I can confirm other types are not working, only csv, tsv, json....
maybe its because its written in hebrew...

**Comment by TitaniumHocker** [comment] 2020-08-30 23:41
Try to install tablib with option `xlsx` or `xls`, like this:
```
pip install tablib[xlsx]
```

**Comment by TheNcar** [comment] 2020-08-30 23:43
> Try to install tablib with option `xlsx` or `xls`, like this:
> ```
> pip install tablib[xlsx]
> ```

Hey, obviously I tried that.
Downloading and earlier version of flask-admin solved this problem

**Comment by TitaniumHocker** [comment] 2020-08-30 23:50
Can't reproduce this with exporting in xlsx format.
I'm using flask-admin from master branch and installed tablib with xlsx option, I also added some text on hebrew to my data.

**Comment by TitaniumHocker** [comment] 2020-09-11 12:31
@TheNcar if your problem is solved, can you pls close the issue?

**Closed** 2020-09-11 12:32 UTC

**Comment by t-huyeng** [comment] 2020-12-07 10:13
hey, I do have the same problem. 
Can you specify your Flask-Admin and tablib version @TitaniumHocker ?
Mine are 
```
Name: Flask-Admin
Version: 1.5.7
```

```
Name: tablib
Version: 2.0.0
```
Since I do not want to downgrade to 1.4 I hope the issue can be fixed otherwise. 

Thanks.

**Comment by t-huyeng** [comment] 2020-12-07 10:27
I was able to fix my problem with 
`$ pip install "tablib[all]"`
instead of only
`$pip install "tablib[xlsx]"`

So this is probably  a tablib issue. Now it is working just fine.
