### ISSUE TITLE
Search related model fields does not produce the correct query

### ISSUE THREAD

**Issue by dzhou** [flask-admin/flask-admin#773] opened 2015-01-22 23:18 UTC
When I have fields from related (Sqlalchemy) model in column_searchable_list, it's not producing the right search results. This works in 1.0.8 and broke after I upgraded flask-admin to 1.0.9. 

```
class Parent(db.Model, BaseModel):  
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), default="", index=True)   
    child = relationship("Child", backref="parent")

class Child(db.Model, BaseModel):
    id = db.Column(db.Integer, primary_key=True)
    name1 = db.Column(db.String(100), default="", index=True)
    parent_id = db.Column(db.Integer, db.ForeignKey('parent.id'), index=True, nullable=False)
```

```
# config for flask-admin
column_searchable_list = (Company.name, 'name1',)
```

```
# the query when I tried search, looks like it's not doing a join
<query statement="SELECT .. FROM child, parent
WHERE lower(parent.name) LIKE lower(%s) OR lower(child.name1) LIKE lower(%s) ORDER BY child.id DESC
 LIMIT %s, %s" parameters=('%test%', '%test%', 0, 100) duration=0.003>
```

**Comment by pawl** [comment] 2015-01-23 01:40
@tandreas spotting this same issue on sorting, but I've been unable to reproduce it in the tests: https://github.com/pawl/flask-admin/commit/d38d6d3e0965c2ad5c715c8899b6201e2e3affec

The issue with sorting seems to occur only in MySQL, even with the newest version of flask-admin. By the way - if you have a filter on one of the related columns, it will probably join correctly.

To fix sorting, I changed this: https://github.com/mrjoes/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L449

To:
```
                else:
                    join_tables, column = self._get_field_with_path(c)

                    result[c] = column

                    if join_tables:
                        self._sortable_joins[c[0]] = join_tables
```

So, your issue is probably around this area?: https://github.com/mrjoes/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L488

**Comment by pawl** [comment] 2015-01-23 02:14
Nevermind, these tests actually passes under mysql too: https://github.com/pawl/flask-admin/commit/d38d6d3e0965c2ad5c715c8899b6201e2e3affec

What would I need to change to reproduce the issue?

**Comment by pawl** [comment] 2015-01-26 20:08
@dzhou can you create a gist that reproduces the issue?

**Comment by pawl** [comment] 2015-01-27 05:17
Here's the gist: https://gist.github.com/pawl/72d15731a1bc9c8b1188

`column_searchable_list` works on relations and produces the correct query. I don't think this is an issue with the current version of flask-admin. However, sorting had a problem and that's fixed now.

Can we close this until someone can provide code that can reproduce the issue?

**Comment by dzhou** [comment] 2015-01-27 05:33
Can you try that gist with mysql db? 
When I tried to search for "a" in child, it's returning wrong results.

![image](https://cloud.githubusercontent.com/assets/82108/5914020/c8481312-a5bb-11e4-935b-4f6e07073ec6.png)

**Comment by pawl** [comment] 2015-01-27 05:49
Ah, looks like it's not working with `Child.child_name` or Parent.parent_name`, but it will work with this:

```
class ModelAdmin(sqla.ModelView):
    column_searchable_list = ('child.child_name', 'parent_name',)


class Model2Admin(sqla.ModelView):
    column_searchable_list = ('parent.parent_name', 'child_name',)
```

**Comment by pawl** [comment] 2015-01-27 16:52
@dzhou This should be fixed in master now. Can you verify?

**Closed** 2015-04-22 07:08 UTC
