### ISSUE TITLE
Support for ONETOMANY for inline models

### ISSUE THREAD

**Issue by cancan101** [flask-admin/flask-admin#1717] opened 2018-10-03 19:08 UTC
I have two models: `Employee` and `Invitation`. An Employee my have many invitations. That being said I would like to simultaneously create a new `Invitation` as well as an associated `Employee`. I cannot do that since the logic is limited to MANYTOONE relationships:
```python
        for prop in target_mapper.iterate_properties:
            if hasattr(prop, 'direction') and prop.direction.name in ('MANYTOONE', 'MANYTOMANY'):
                if issubclass(model, prop.mapper.class_):
                    reverse_prop = prop
                    break
```

**Comment by petrus-jvrensburg** [comment] 2018-10-31 11:10
duplicate of #1405

**Closed by petrus-jvrensburg** 2018-10-31 11:10 UTC
