### ISSUE TITLE
form_widget_args does not work in subdocument

### ISSUE THREAD

**Issue by cybertoast** [flask-admin/flask-admin#663] opened 2014-10-16 14:15 UTC
This is an extension (or resurrection?) of #361. 
The following pertains to 1.0.8 and the master branch, both of which exhibit the behavior.

From what I can tell it's still a problem with EmbeddedDocumentField (i.e. form_subdocuments). When I attempt to set 'form_widget_args' on the subdocument it still does not work (though form_columns and form_args works fine). My definition is:

```
form_subdocuments = {
    'metadata': {
        'form_columns': ('artist', 'album',),
        'form_widget_args': {
            'artist': { 'rows': 50 }
        }
    }
}
```

However, if I add a form_rules key then it all works fine! But I don't understand why form_rules are needed in order to get the form_widget_args to work. Basically the following works:

```
form_subdocuments = {
    'metadata': {
        'form_rules`: ('artist', 'album',)
        'form_widget_args': {
            'artist': { 'rows': 50 }
        }
    }
}
```

**Comment by mrjoes** [comment] 2015-06-11 01:40
Ugh, this one is probably very old, but I was not able to reproduce it.

**Comment by piersharding** [comment] 2015-11-24 01:54
I managed to reproduce this: 
```
class InlineModelForm(InlineFormAdmin):
    form_excluded_columns = ('created_on',)
    form_rules = ('updated_on', 'comment',)
    form_widget_args = {
        'updated_on': {
            'disabled': True,
        },
    }
```

Without the form_rules, form_widget_args was not applied.

Cheers,
Piers Harding.

**Comment by petrus-jvrensburg** [comment] 2018-10-18 12:43
Closing this now, but please re-open if it's still a problem.

**Closed by petrus-jvrensburg** 2018-10-18 12:43 UTC
